export const buttons = {
  'zero': { area: 'zero', span: "0", type: 'field',  },
  'one': { area: 'one', span: "1", type: 'field',  },
  'two': { area: 'two', span: "2", type: 'field',  },
  'three': { area: 'three', span: "3", type: 'field',  },
  'four': { area: 'four', span: "4", type: 'field',  },
  'five': { area: 'five', span: "5", type: 'field',  },
  'six': { area: 'six', span: "6", type: 'field',  },
  'seven': { area: 'seven', span: "7", type: 'field',  },
  'eight': { area: 'eight', span: "8", type: 'field',  },
  'nine': { area: 'nine', span: "9", type: 'field',  },
  'dot': { area: 'dot', span: ".", type: 'field' },
  'clear': { area: 'clear', span: "C", type: 'action' },
  'plus': { area: 'plus', span: "+", type: 'action' },
  'minus': { area: 'minus', span: "-", type: 'action' },
  'divide': { area: 'divide', span: "/", type: 'action' },
  'multiply': { area: 'multiply', span: "X", type: 'action' },
  'percent': { area: 'percent', span: "%", type: 'action' },
  'reverse': { area: 'reverse', span: "+/-", type: 'action' },
  'equals': { area: 'equals', span: "=", type: 'action' },
};

export const actions = {
  '+': (operand1, operand2) => operand1 + operand2,
  '-': (operand1, operand2) => operand1 - operand2,
  'X': (operand1, operand2) => operand1 * operand2,
  '/': (operand1, operand2) => operand1 / operand2,
  '+/-': (operand) => -operand,
  '%': (operand) => operand / 100,
};
